heat_template_version: 2013-05-23

description: |
  Simple template to deploy Redis on a cloud server

parameters:
  key-name:
    type: String
    description: Name of a nova ssh keypair to use for server access
  image:
    # currently requires an image id; refactor in-progress
    # to accept image names as well as ids
    type: String
    description: Server image id to use
    constraints:
    # only tested on Ubuntu images so far
    - allowed_values:
      - 1bbc5e56-ca2c-40a5-94b8-aa44822c3947
      - 9aa3b52b-1471-413f-8b2b-0fbc756491b4
      - c6f9c411-e708-4952-91e5-62ded5ea4d3e
      - 23b564c9-c3e6-49f9-bc68-86c7a9ab5018
      description: must be a valid Ubuntu image id
  flavor:
    # currently requires an id; refactor in-progress
    # to allow flavor names as well as ids
    type: Number
    description: Server flavor id to use
    constraints:
    - range:
        min: 2
        max: 8
      description: must be a valid flavor id

resources:
  redis:
    type: Rackspace::Cloud::Server
    properties:
      key_name: { get_param: key-name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      user_data: |
        apt-get install -y build-essential
        wget http://download.redis.io/releases/redis-2.6.16.tar.gz 
        tar xzf redis-2.6.16.tar.gz 
        cd redis-2.6.16 
        make
        make install
        cd utils
        yes '' | ./install_server.sh
        cd ../../
        rm -rf redis-2.6.16
        rm redis-2.6.16.tar.gz

outputs:
  ssh:
    value: 
      str_replace:
        template: ssh root@$host
        params:
          host:
            get_attr:
            - redis
            - PublicIp
    description: ssh to the redis host
  verify:
    value:
      str_replace:
        template: redis-cli -h $host ping
        params:
          host:
            get_attr:
            - redis
            - PublicIp
    description: verify the redis server via redis-cli
